version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: kn_discord
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
